# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(allow_unicode=True, help_text='title alias for SEO', unique=True, verbose_name='Slug')),
                ('description', models.CharField(blank=True, help_text='simple description text', max_length=100, verbose_name='Description')),
                ('content', models.TextField(verbose_name='Content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='Modifiy Date')),
            ],
            options={
                'db_table': 'blog_posts',
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
                'ordering': ('-modify_date',),
            },
        ),
    ]
